# Uncomment the next line to define a global platform for your project
# platform :ios, '12.1'

target 'UAsk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  source 'https://github.com/CocoaPods/Specs.git'

  # Pods for UAsk

  target 'UAskTests' do
    # pod 'Firebase/Core'
    inherit! :search_paths
    # Pods for testing
  end

  target 'UAskUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
